### ISSUE TITLE
The "Change" value needs to be adjusted with the currency exchange selected

### ISSUE THREAD

**Issue by irv0735** [ARevampedLifeCoding/project-1#44]
% would not be affected, but the "points" value would.

**Comment by irv0735** [comment]
Is there a way we can do this with a data-attribute?  maybe create a data-currency attribute that is added to all values on the page that represent a currency value and then apply the currency filter to any item that has the data-currency attribute?

**Comment by satishiyer31** [comment]
This is fixed. Right now I am manually applying the currency adjustment to a set of fields. Adding them  to a common class or applying data attribute will be cleaner. We can leave this for future development. The immediate bug is fixed.
