### ISSUE TITLE
Need 3 additional cards on the stock details page to "fill out" the display

### ISSUE THREAD

**Issue by irv0735** [ARevampedLifeCoding/project-1#58]
first card on bottom row has 3 lines of data, so we should think about doing the same on these for consistent spacing.
Open to ideas. Here is one to consider:

- Financial Growth
1. Growth Revenue
2. Growth GP
3. 3 year revenue growth per share

**Comment by satishiyer31** [comment]
Add Financial ratios and readjusted the cards to align.
